Singup
Woynert/buenavida-back pull request #12
Opened 2022-11-01 02:40 UTC by andres123dbh

Closes #10

- Endpoint singn In
	- Comprueba que los campos (Nombre,Apellido,Correo y Contraseña) no esten vacios
	- Comprueba que el correo tenga formato de correo
	- Comprueba que la contraseña cumpla con las reglas
	- Comprueba si el usuario ya existe
	- Guarda usuario en mongodb

2022-11-01 18:42 UTC, Woynert requested changes

2022-11-01 18:42 UTC, Woynert commented on src/controller/session.go
> +	c.IndentedJSON(http.StatusOK, gin.H{"message": result.InsertedID})
En registro exitoso es mejor que envíe un mensaje en lugar del ID

2022-11-02 02:23 UTC, andres123dbh commented on src/controller/session.go
> +	c.IndentedJSON(http.StatusOK, gin.H{"message": result.InsertedID})
Listo

2022-11-02 13:54 UTC, merged

2022-11-02 13:55 UTC, Woynert commented
Genial!